### ISSUE TITLE
Doesn't build with base-4.9.0.0

### ISSUE THREAD

**Issue by bgamari** [nikita-volkov/hasql-transaction#2]
It looks like you may need to add a dependency on `base`,

```
[1 of 3] Compiling Hasql.Transaction.Prelude ( library/Hasql/Transaction/Prelude.hs, dist/build/Hasql/Transaction/Prelude.o )

library/Hasql/Transaction/Prelude.hs:15:1: error:
    Failed to load interface for ‘Control.Monad.IO.Class’
    It is a member of the hidden package ‘base-4.9.0.0’.
    Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

**Comment by nikita-volkov** [comment]
Fixed
